- yt_astro_analysis/halo_finding/rockstar/rockstar.py
This allows the docs to build properly without Rockstar installed (e.g, on readthedocs.)
> Allow rockstar module to import if Rockstar not installed.

- .travis.yml
- setup.py
The log output from travis is so long as to make it difficult to find the errors. This sets the loglevel to warn to hopefully bring that down a bit.  I also uncommented the python 3 and minimum dependency python 2 tests because it looks like they get run anyway.
> make test output less verbose

- setup.py
I mistakenly disallowed Python 3.5 in PR #22 and broke the readthedocs build. This fixes that.
> [bugfix] Fix version check in setup.

- doc/Makefile
- doc/source/conf.py
This gets rid of the warnings from the docs build. In the future, we can add a docs test.
> Add napoleon extension and error out on warnings in docs build.

- .travis.yml
- yt_astro_analysis/cosmological_observation/light_cone/light_cone.py
- yt_astro_analysis/cosmological_observation/light_cone/light_cone_projection.py
- yt_astro_analysis/cosmological_observation/light_cone/tests/test_light_cone.py
This resolves Issue #36. There were a few places with improper handling of the projected weight field. The behavior of the code suggests that some functionality was not updated for changes to projections, so this has likely been broken for quite some time. I'll let the test suite run and then add a new test.
> [bugfix] fix light cone projections with weight fields

- yt_astro_analysis/halo_analysis/halo_catalog.py
The HaloCatalog progress bar had an unnecessary `update` call and was missing a `finish` call.
> [bugfix] Fix HaloCatalog progress bar

- yt_astro_analysis/halo_finding/rockstar/rockstar.py
This makes the error message show up in the RuntimeError instead of the logging stream (which might be turned off). I also tried to phrase the error message in a clearer way.
> clarify rockstar error message about using the wrong number of MPI processes

- yt_astro_analysis/halo_analysis/halo_catalog.py
Some frontends (e.g. AHF) don't use these field names in `ds.field_list` and instead set up aliases. These fields are still in `derived_field_list` and are accessible so the fix is just to look in `derived_field_list`.
> check derived_field_list for base fields

- yt_astro_analysis/cosmological_observation/cosmology_splice.py
This fixes the logic on next/previous splices to allow for a single existing dataset.
> [bugfix] allow cosmology splice from a single dataset

- .circleci/config.yml
- setup.py
This adds weekly tests and updates the python versions used.
It also explicitly drops Python 2 support. We haven't been testing Python 2 for a while, nor has there really been any development, so I think this is ok to do.
> Update python version and add weekly tests

- .circleci/config.yml
- setup.py
~~This adds a python 3.8 tests and some weekly tests on Mondays.~~
Apparently, I did that a while ago. This removes Python 3.6 and 3.7 from the tests and moves them to the weekly cron tests with Python 3.5 and 3.8.
> Remove intermediate Python versions from testing

- .circleci/config.yml
- doc/source/halo_catalogs.rst
- yt_astro_analysis/halo_analysis/halo_catalog.py
- yt_astro_analysis/halo_analysis/halo_finding_methods.py
- yt_astro_analysis/halo_finding/halo_objects.py
This PR adds the ability to save the particle ids belonging to each halo to the halo catalogs. This can be merged on its own, but will not be of use until support is added to yt to read the particles in. I'll update when that's ready.
This also fixes a bug introduced a while back when we stopped combining the halo lists before saving in which halo ids were no longer unique.
There's a bit of a chicken and egg problem with the yt PR to read in the particles. I'd argue this should be merged first since there are a bit lower stakes. After that, the yt PR can be merged, then I will issue another PR here adding relevant tests.
If anyone would like to tests this out, they'll need to use changes from my fork of yt. Something like this should work:
```
get fetch https://github.com/brittonsmith/yt …
```
> save halo particles for fof and hop

- .circleci/config.yml
- README.md
- doc/source/Installation.rst
- setup.py
- yt_astro_analysis/halo_finding/rockstar/rockstar.py
- yt_astro_analysis/halo_finding/rockstar/rockstar_interface.pyx
- yt_astro_analysis/halo_finding/tests/test_rockstar.py
In this PR, I've extracted the relevant changes from the [Agora project yt PR](https://bitbucket.org/yt_analysis/yt/pull-requests/1560/yt-agora/diff) to update the rockstar interface to use rockstar-galaxies. It was too difficult to preserve the history, so I overlaid the changed files and did a fair amount of cleanup until the diff looked sensible. There may still be more things to clean up, but this first pass was mainly about typos, extra whitespace, applying later changes, and making things work with Python 3.
I think this is a safe move to make. There have been very few changes to rockstar-galaxies in recent years and probably longer since the API changed. There are also some other stable forks (like [this one](https://bitbucket.org/jwise77/rockstar-galaxies)) that can be used and …
> update rockstar interface to rockstar-galaxies

- .circleci/config.yml
The tests are currently failing because yt changed its default branch from master to main.  This failure is also causing Trident and any package that depends on `yt_astro_analysis` to also fail.  
This PR should address this problem and fix the failing tests.
> Changing downloaded yt branch to main to fix tests.

- yt_astro_analysis/halo_finding/rockstar/rockstar_interface.pyx
This fixes the rockstar frontend, which was broken in recent version of yt as the __iter__ function was removed.
The same behaviour can still be achieved the iter keyword.
> Fix iterator

- .circleci/config.yml
- yt_astro_analysis/cosmological_observation/light_cone/tests/test_light_cone.py
- yt_astro_analysis/halo_analysis/tests/test_halo_finders.py
- yt_astro_analysis/halo_finding/tests/test_rockstar.py
- yt_astro_analysis/utilities/testing.py
This moves `requires_sim` and `can_run_sim` into this repo as they have been deprecated in yt. This is the only place they are used.
> Move yt testing functions into yt_astro_analysis

- .circleci/config.yml
- setup.py
This updates the python versions used for testing and add python 3.9. I also switched to a date-based naming system for the caches to help me keep track and fixed an issue with the naming of the testing file.
> Update python versions on circleci

- yt_astro_analysis/cosmological_observation/cosmology_splice.py
The max_box_fraction parameter was not being set if you only call `plan_cosmology_splice`. This adds it as a keyword arg. The example in the docstring now works for me.
> [bugfix] Add max_box_fraction to plan_cosmology_splice.

- setup.py
- setupext.py
- tests/__init__.py
This is mainly to limit the version of setuptools as the latest version has removed the use_2to3 function, breaking a few things. In doing so, I came across a bunch of unused setup functionality leftover from when the code was taken out of yt.
> fix setuptools version and remove unused setup functions

- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
This adds a ``restart`` keyword to the rockstar halo finder allowing it to be restarted from the first uncompleted snapshot.
> Add restart option for rockstar

- .circleci/config.yml
This drops support for python 3.6 following the same move in yt. I've also updated python versions and caches.
> Drop support for python 3.6

- .circleci/config.yml
- setup.cfg
- setup.py
A couple simplifications that I found while working on setting up automatic wheels
> ENH: simplify test scripts and migrate some static metadata from setup.py to setup.cfg

- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar_interface.pyx
Some frontends do not define the "particle_type" field, but it is barely needed. This allows halo finding to proceed if it doesn't exist and also does not access it if we do not actually need it (which is the default).
> only access particle_type field in rockstar if it exists and is needed

- .github/workflows/wheels.yaml
Based off #116
Fix #117
inspired by https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
opening as a draft
@brittonsmith, we need to first create a PYPI_TOKEN for this to work, I can walk you through it if you want
> REL: automate wheels publication to PyPI

- pyproject.toml
- setup.cfg
noticed this while working on the conda-forge recipe. This upper limit is arbitrary and doesn't correspond to a known issue, hence it has the potential of causing more harm than good, might as well remove it now since we're doing a patch release
> remove overly protective upper limit to h5py version

- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
The available particle types won't be known unless the index is initialized first. This can happen when doing halo finding on time-series.
> Make sure to initialize index before checking particle types.

- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar_interface.pyx
This prevents integer overflow when the number of particles exceeds the 32 bit signed integer limit. I've tested this out on a dataset producing this error and it works.
> Make total particles a 64 bit integer.

- yt_astro_analysis/halo_analysis/halo_catalog/halo_catalog.py
Rockstar manages its own output directory creation. Prior to this, if you ran rockstar, you end up with halo catalogs in rockstar's output directory as determined by the `outbase` rockstar option and then an empty `halo_catalogs` directory written by the `HaloCatalog`. This PR just adds a little sync-up between those two so you don't end up with this extra directory.
> Set output directory properly for rockstar halo finder.

- README.md
- doc/source/Installation.rst
Conda changed the package name associated with this package from `yt_astro_analysis` to `yt-astro-analysis`, i.e., changing the underscores to hyphens. If you do:
```
conda install yt_astro_analysis
```
you will be stuck on version 1.0. You can only get 1.1 and beyond by installing with the new name. With pip, you can install with either naming convention. For simplicity, I've changed the conda/pip installation instructions to both use hyphenized name. I've also updated the conda badge to point at the right package.
> Update package name for conda/pip installation.

- .circleci/config.yml
This should prevent the testing on circleci from timing out.
Fixes Issue #146.
> Increase timeout on data download.

- .github/workflows/wheels.yaml
ref: https://github.com/actions/runner-images/issues/6002
> BLD: switch ubuntu image to 20.04 (18.04 image is deprecated)

- .github/workflows/wheels.yaml
- yt_astro_analysis/halo_analysis/halo_finding/fof/EnzoFOF.c
- yt_astro_analysis/halo_analysis/halo_finding/hop/EnzoHop.c
Cherry picking the relevant bits from #163
- BLD: add CPython 3.11 to supported wheels
- BLD: fix building on CPython 3.11 (migrate away from deprecated numpy C-API)
> BLD: build wheels for Python 3.11

- .github/workflows/wheels.yaml
get rid of deprecation warnings
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
> MNT: bump github action versions

- pyproject.toml
- yt_astro_analysis/halo_analysis/halo_catalog/halo_callbacks.py
This isn't going to make a difference in builds while yt itself depends on more-itertools but it seems somewhat abusive to require it here just for one simple function used in a single place.
> BLD: drop dependency on more_itertools

- .pre-commit-config.yaml
- doc/source/halo_catalog.rst
- pyproject.toml
- yt_astro_analysis/cosmological_observation/cosmology_splice.py
- yt_astro_analysis/cosmological_observation/light_cone/light_cone.py
- yt_astro_analysis/halo_analysis/halo_catalog/halo_catalog.py
- yt_astro_analysis/halo_analysis/halo_catalog/plot_modifications.py
- yt_astro_analysis/halo_analysis/halo_finding/halo_objects.py
- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar.py
- yt_astro_analysis/ppv_cube/tests/test_ppv.py
- yt_astro_analysis/radmc3d_export/tests/test_radmc3d_exporter.py
black 23.1.0 is now able to infer target version from the project metadata (namely `requires-python = ">=3.8"`) so it's a small opportunity for simplifying config and reducing the number of places where we need to keep track of supported versions
I'm also removing the `line-length` parameter because it's set to the default value, so it's not doing anything
> STY: upgrade black to 23.1.0

- README.md
- doc/extensions/config_help.py
- doc/extensions/pythonscript_sphinxext.py
- doc/extensions/yt_colormaps.py
- doc/extensions/yt_cookbook.py
- doc/source/conf.py
- pyproject.toml
see https://github.com/yt-project/yt/pull/4444
> STY: activate flake8-comprehensions (ruff)

- yt_astro_analysis/halo_analysis/halo_finding/fof/EnzoFOF.c
fix the following compilation warning
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -DOPENSSL_NO_SSL3 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/build-env-sk2pigg1/include -I/Users/robcleme/.pyenv/versions/3.9.17/include/python3.9 -I/private/var/folders/xh/yfmp7l9n3x50ln2yvrndt7c801pbkm/T/build-env-sk2pigg1/lib/python3.9/site-packages/numpy/core/include -c yt_astro_analysis/halo_analysis/halo_finding/fof/EnzoFOF.c -o …
```
> MNT: cleanup free of uninitialized variable

- pyproject.toml
- setup.py
- yt_astro_analysis/halo_analysis/halo_finding/rockstar/rockstar_interface.pyx
Opening as a draft. Build already works (locally) but there may be some performance regressions. Hopefully it'll show in CI.
> BLD: switch to Cython 3.0, forbid deprecated Numpy C API in generated code

- pyproject.toml
- setup.py
> BLD: migrate from oldest-supported-numpy to NPY_TARGET_VERSION (Python >= 3.9)

- doc/source/Installation.rst
- setup.py
rockstar can now be installed through conda. This simplifies the installation process as it needs not be compiled manually.
Eventually on Linux, we may want (or not?) to set rockstar as a hard dependency on our conda-forge build so that the support is automatic.
> Support installation of rockstar through conda

- .circleci/config.yml
- pyproject.toml
- setup.py
proposed solution to fix CI, which is currently failing because the dev version of yt doesn't support Python 3.8 anymore.
includes changes from #221
> DEP: drop support for CPython 3.8

- doc/source/PPVCube.ipynb
This fixes another incompatibility seen in doc/source/PPVCube.ipynb
There are other issues with this notebook but I'll get back to it after #225 is dealt with.
> BUG: fix usage of deprecated (and removed) clobber argument from astropy

- doc/source/PPVCube.ipynb
> BUG: fix a couple bugs in PPVCube notebook

- .github/workflows/wheels.yaml
This replaces the need to use a token to upload to Pypi. Instead, one configures the project on Pypi to accept authentication from GitHub (https://pypi.org/manage/project/yt-astro-analysis/settings/publishing/).
This should allow us to completely remove the need for authorization tokens in the secrets.
> Do not use tokens for Pypi uploads

- .pre-commit-config.yaml
- pyproject.toml
- yt_astro_analysis/halo_analysis/halo_finding/halo_objects.py
I couldn't resist when I saw https://github.com/conda-forge/yt_astro_analysis-feedstock/pull/24
I haven't thoroughly checked this locally so I'm mostly just crossing fingers 🤞🏻
> DEP: unpin numpy (declare numpy 2.0 compatibility)

- yt_astro_analysis/halo_analysis/halo_finding/hop/hop_hop.c
Somehow merging #255 broke compilation. This fixes the compilation issue:
```
$ python -m pip install -e -v .
[...]
gcc-9 -fno-strict-overflow -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/cphyc/miniforge3/envs/py312/include -fPIC -O2 -isystem /home/cphyc/miniforge3/envs/py312/include -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DNPY_TARGET_VERSION=NPY_1_19_API_VERSION -I/home/cphyc/miniforge3/envs/py312/include/python3.12 -I/home/cphyc/miniforge3/envs/py312/lib/python3.12/site-packages/numpy/_core/include -c yt_astro_analysis/halo_analysis/halo_finding/hop/hop_hop.c -o build/temp.linux-x86_64-cpython-312/yt_astro_analysis/halo_analysis/halo_finding/hop/hop_hop.o
In file included from /home/cphyc/miniforge3/envs/py312/lib/python3.12/site-packages/numpy/_core/include/nump …
```
> Fix compilation issue

- .circleci/config.yml
- pyproject.toml
- requirements/tests.txt
- Update oldest Python version tested to Py3.10, newest is 3.13 [note: this isn't strictly enforced yet].
- Switch from `nose` to `pynose` (waiting for #238 or similar to be merged in).
> Restore CI
