- yt_astro_analysis/halo_finding/rockstar/rockstar.py
- yt_astro_analysis/halo_finding/rockstar/rockstar_interface.pyx
For the record, this was done with:
```
git remote-add yt <yt repo>
git fetch yt
git cherry-pick <changes>
```
I did the cherry pick for each commit individually.
> Backporting rockstar fixes

- yt_astro_analysis/cosmological_observation/light_cone/light_cone.py
- yt_astro_analysis/halo_analysis/enzofof_merger_tree.py
- yt_astro_analysis/halo_analysis/halo_callbacks.py
- yt_astro_analysis/halo_finding/halo_objects.py
- yt_astro_analysis/ppv_cube/tests/test_ppv.py
This should be the last of them.  Tests will likely fail since one is a test change.
> Backporting the last changes from analysis_modules.

- .codecov.yml
- .travis.yml
- setup.py
This updates the automated tests and package setup in the following ways:
* cache the test answers and rockstar build
* switch to using jobs and add a docs build test
* add codecov support
* declare dev requirements and use those for installation in travis
> testing updates

- README.md
- doc/source/Installation.rst
I think I need to merge https://github.com/conda-forge/yt_astro_analysis-feedstock/pull/1 before installing from conda-forge actually works so best to hold off on this until that's merged.
> document installing from conda-forge. fixes #30

- CITATION.rst
Author list order following originally stated number-of-commits policy.
Official zenodo entry [here](https://zenodo.org/record/1458961#.XABVkV5Kht9).
> Add Anthony Scopatz to author list.

- CITATION.rst
> Add John ZuHone to author list.

- setup.py
So we can continue testing with yt-dev.
> Add pytest to dev requirements.

- .circleci/config.yml
- setup.py
- yt_astro_analysis/halo_analysis/halo_callbacks.py
- yt_astro_analysis/halo_finding/halo_objects.py
- yt_astro_analysis/halo_finding/rockstar/rockstar.py
Following yt's migration to toml (https://github.com/yt-project/yt/pull/2981), this project needs an update.
This also fixes the `ensure_list` missing function.
> Support new config file format

- .circleci/config.yml
- yt_astro_analysis/ppv_cube/ppv_cube.py
> Update function name.

- setup.py
There will be more substantial updates to the project management soon, but I'd like to get this in there to head off any more confusion about compatibility with older versions of yt.
> Update required yt version.

- .circleci/config.yml
This should fix the circleci issues.
> Change apt-get to apt in ci script.

- .github/workflows/wheels.yaml
Fix #107
I've run the workflow successfully on my fork here https://github.com/neutrinoceros/yt_astro_analysis/actions/runs/1526300758
> MNT: add workflow to automate wheels build

- setup.cfg
forgot this on our release checklist ...
> REL: bump version number to 1.1.0

- .github/workflows/wheels.yaml
Hopefully this should fix wheels upload
> REL: fixup publish workflow

- yt_astro_analysis/halo_analysis/halo_catalog/__init__.py
- yt_astro_analysis/halo_analysis/halo_catalog/plot_modifications.py
> BUG: fix broken example with halo plotting

- .circleci/config.yml
- doc/source/conf.py
Right now, fix CI. In the future, avoid raising a warning in yt.
> TST: hotfix CI (workaround upstream change of behaviour)

- yt_astro_analysis/cosmological_observation/light_cone/light_cone.py
> BUG: fix compatibility with numpy 1.24 (numpy.float was removed)

- .circleci/config.yml
Another go at fixing #182 as suggested by @xarthisius
> TST: ensure test dependencies are correctly installed in CI

- yt_astro_analysis/radmc3d_export/RadMC3DInterface.py
see https://github.com/numpy/numpy/pull/23314
> BUG: handle deprecation warning from numpy 1.25 (np.product is deprecated in favour of np.prod)

- yt_astro_analysis/halo_analysis/halo_finding/fof/EnzoFOF.c
- yt_astro_analysis/halo_analysis/halo_finding/hop/EnzoHop.c
- yt_astro_analysis/halo_analysis/halo_finding/hop/hop_hop.c
- yt_astro_analysis/halo_analysis/halo_finding/hop/hop_regroup.c
- yt_astro_analysis/halo_analysis/halo_finding/hop/hop_smooth.c
- yt_astro_analysis/halo_analysis/halo_finding/hop/smooth.h
fix a bunch of compilation warnings
> MNT: cleanup unused variables

- .readthedocs.yml
- doc/requirements.txt
trying to fix #233
I expect a couple iterations might be needed
> DOC: pin doc requirements
